import type { Metadata } from "next";
import "./globals.css";
import { Urbanist } from "next/font/google"
import "/public/assets/css/main.css"
import { StoreProvider } from "@/store/StoreProvider";

const urbanist = Urbanist({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: "--urbanist",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Savaari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${urbanist.variable}`}>
          
          {children}
        </body>
      </html>
      </StoreProvider>
  );
}
